# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 202ffc89e4ec7c303336bab3cf5f0838f5212380c0a51648eec7112aab921bdcc435fee908e1fe6fb05106db9879804c05009133106adf83525b6478db3abe81

test:
  secret_key_base: 9b95d30fae745613eaabab71fdba499bf65880be3d4dfa46a9871431da6cd5d70a2bcdc890b84330ca11d45debe0c4d3f90dad8721488efb425ad9891c8021b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
